version: '3.7'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=daria
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
      
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
 
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  
volumes:
  my-db: